name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # Add the env block at the job level
    env:
      API_KEY: ${{ secrets.API_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest uvicorn python-multipart
          # You might also need to install the ODBC driver in the container
          # This is a critical step for your workflow to connect to the database
          # Add the installation steps here if running in a clean runner environment
          # Example for Ubuntu:
          # sudo apt-get update
          # sudo apt-get install -y msodbcsql18 unixodbc-dev

      - name: Run tests
        run: |
          pytest -v tests/integration/test_api.py

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Extract Azure credentials
        id: extract-creds
        run: |
          echo "ACR_USERNAME=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientId')" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientSecret')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ricky2509acr.azurecr.io
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ricky2509acr.azurecr.io/anomaly-detector-api:latest

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: ricky2509acr
          containerAppName: anomaly-detector-api-service
          resourceGroup: AnomalyDetectorRG
          imageToDeploy: ricky2509acr.azurecr.io/anomaly-detector-api:latest
          acrUsername: ${{ env.ACR_USERNAME }}
          acrPassword: ${{ env.ACR_PASSWORD }}
