name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest uvicorn python-multipart

      - name: Run tests
        run: |
          pytest -v tests/integration/test_api.py

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Log in to Azure Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ricky2509acr.azurecr.io
      #     username: ${{ secrets.ACR_USERNAME }}
      #     password: ${{ secrets.ACR_PASSWORD }}
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ricky2509acr.azurecr.io
          username: ${{ secrets.AZURE_CREDENTIALS.clientId }}
          password: ${{ secrets.AZURE_CREDENTIALS.clientSecret }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ricky2509acr.azurecr.io/anomaly-detector-api:latest

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: ricky2509acr
          containerAppName: anomaly-detector-api-service
          resourceGroup: AnomalyDetectorRG
          imageToDeploy: ricky2509acr.azurecr.io/anomaly-detector-api:latest
